### ISSUE TITLE
Change of delimiters, separators 

### ISSUE THREAD

**Issue by wolfgamM** [MajicDesigns/MD_Menu#12]
Hello,

delimiters, separators and other special characters are defined in MD_Menu_lib.h.
e.g: const char MNU_DELIM_L[] = "<"; 

It would be nice if they could be changed. 
Beeing defined as constants, reassigning a new value is impossible.

regards
Wolfgang

**Comment by MajicDesigns** [comment]
> Being defined as constants, reassigning a new value is impossible

They are defined as constants so that they CAN be changed easily by editing the value in one place. The alternative is to have explicit constants all through the code, which would be a nightmare for any changes.

I suspect what you mean is that you cannot change these at run time. You can easily do that by adding a method for that if you feel the need to do this. In most situations I would expect that the preferred delimiter is set once in the libraries and then never changed. At that point, however, every other parameter should also be made configurable ...
